# Generated by Django 3.2.3 on 2022-04-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entrid', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=20)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Equity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=50)),
                ('Idea', models.TextField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Equity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Investor', models.ManyToManyField(to='Xharktanks.Investors')),
            ],
        ),
    ]
