# Generated by Django 3.2.3 on 2022-04-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xharktanks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entre',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='entre',
            old_name='Name',
            new_name='entrepreneur',
        ),
        migrations.RenameField(
            model_name='entre',
            old_name='Investor',
            new_name='offers',
        ),
        migrations.RenameField(
            model_name='entre',
            old_name='Idea',
            new_name='pitchIdea',
        ),
        migrations.RenameField(
            model_name='entre',
            old_name='Title',
            new_name='pitchTitle',
        ),
        migrations.RenameField(
            model_name='investors',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='investors',
            old_name='Name',
            new_name='investor',
        ),
        migrations.RemoveField(
            model_name='entre',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='entre',
            name='Equity',
        ),
        migrations.RemoveField(
            model_name='entre',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='investors',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='investors',
            name='Equity',
        ),
        migrations.RemoveField(
            model_name='investors',
            name='entrid',
        ),
        migrations.RemoveField(
            model_name='investors',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='entre',
            name='askAmount',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='entre',
            name='equity',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='investors',
            name='amount',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='investors',
            name='equity',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=20),
        ),
    ]
