# Generated by Django 3.2.3 on 2022-04-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xharktanks', '0002_auto_20220406_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entre',
            name='askAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='entre',
            name='equity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
