# Generated by Django 3.2.3 on 2022-04-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xharktanks', '0003_auto_20220406_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entre',
            name='pitchTitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='investors',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='investors',
            name='equity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
